### ISSUE TITLE
Do we need @nucypher/nucypher-core dependency on taco and pre packages?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/taco-web#400]
It's already a dependency in `shared`, which is a dependency on both `taco` and `pre`.

**Comment by piotr-roslaniec** [comment]
We could re-export the whole `nucypher-core` from `shared` so that the `taco` and `pre` can use them from there, but I don't think it's going to make that much difference. The exports are hidden from the users, and the dependencies are de-duplicated as long as we use the same `nucypher-core` version. 

So I think it boils down to either having them re-exported and benefiting from a simpler `nucypher-core` version management (set it once instead of setting it in three files) vs. having explicit dependency and explicit imports in every package. I think the latter makes some sense since `pre` and `taco` use different concepts from `nucypher-core`, and so putting them into `shared` is a bit stretch. I could make a similar argument for `ethers` usage.

**Comment by cygnusv** [comment]
I see, it makes sense. I'm just concerned that at some moment we end up bumping the nucypher-core version in one place and forget the other.

**Comment by piotr-roslaniec** [comment]
I think I can add something like a monorepo-level resolution to a specific version. I will look into it.

**Comment by cygnusv** [comment]
Thanks, this of course has low priority, so no rush.
